release:
  github:
    owner: volkszaehler
    name: mbmd
before:
  hooks:
  - make assets
builds:
- id: main
  main: main.go
  ldflags:
  - -X github.com/volkszaehler/mbmd/server.Version={{.Version}} -X github.com/volkszaehler/mbmd/server.Commit={{.ShortCommit}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  goarm:
  - "6"
archives:
  - builds:
    - main
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^chore'
    - '^bump'
    - '^docs:'
    - '^test:'
